name: My First Workflow

on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubunut-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          
        - name: Say Hello
          run: echo "Hello world"
