name: My First Workflow

on: push

jobs:
    my_first_job:
        runs-on: ubunut-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Say Hello
              run: echo "Hello world"
